# Generated by Django 2.0.4 on 2018-04-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallForPaper',
            new_name='CallForProposals',
        ),
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/meetups/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/speakers/'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/teams/'),
        ),
        migrations.AlterField(
            model_name='meetupphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='meetups/pics/'),
        ),
    ]
