# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='UpComingMeetups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=100)),
                ('Topic', models.CharField(choices=[('Technical Presentation', 'Technical Presentation'), ('Non-Technical Presentation', 'Non-Technical Presentation'), ('Talks', 'Talks')], max_length=50, null=True)),
                ('Speaker', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Date', models.DateField(default=None)),
                ('Time', models.TimeField(default=None)),
                ('Venue', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pastevents',
            name='pastevents',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meetup.UpComingMeetups'),
        ),
        migrations.AddField(
            model_name='pastevents',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
